import { supabase } from '@/integrations/supabase/client';
import { InvitationError } from '@/types/InvitationWorkflowTypes';

/**
 * Service that wraps database functions for invitation token management
 * This service provides a clean interface to the stored procedures and functions
 * created in the database migration
 */
export class InvitationTokenDatabaseService {

  /**
   * Regenerate a token for an invitation using database function
   * Requirements: 2.5, 6.2
   */
  async regenerateTokenViaDatabase(invitationId: string): Promise<{
    data?: {
      tokenId: string;
      token: string;
      expiresAt: string;
      createdAt: string;
    };
    error?: InvitationError;
  }> {
    try {
      const { data, error } = await supabase.rpc('regenerate_invitation_token', {
        invitation_id_input: invitationId
      });

      if (error) {
        console.error('Error regenerating token via database:', error);
        return {
          error: {
            code: 'DB_REGENERATE_TOKEN_FAILED',
            message: 'Failed to regenerate token via database function',
            details: error
          }
        };
      }

      if (!data || data.length === 0) {
        return {
          error: {
            code: 'NO_TOKEN_GENERATED',
            message: 'No token was generated by the database function'
          }
        };
      }

      const tokenData = data[0];
      return {
        data: {
          tokenId: tokenData.token_id,
          token: tokenData.token,
          expiresAt: tokenData.expires_at,
          createdAt: tokenData.created_at
        }
      };
    } catch (error) {
      console.error('Exception regenerating token via database:', error);
      return {
        error: {
          code: 'DB_REGENERATE_TOKEN_EXCEPTION',
          message: 'Exception occurred during database token regeneration',
          details: error
        }
      };
    }
  }

  /**
   * Get token information for an invitation using database function
   * Requirements: 4.2, 4.3
   */
  async getTokenInfoViaDatabase(invitationId: string): Promise<{
    data?: {
      tokenId: string;
      token: string;
      expiresAt: string;
      usedAt: string | null;
      createdAt: string;
      isExpired: boolean;
      isUsed: boolean;
    };
    error?: InvitationError;
  }> {
    try {
      const { data, error } = await supabase.rpc('get_invitation_token_info', {
        invitation_id_input: invitationId
      });

      if (error) {
        console.error('Error getting token info via database:', error);
        return {
          error: {
            code: 'DB_GET_TOKEN_INFO_FAILED',
            message: 'Failed to get token info via database function',
            details: error
          }
        };
      }

      if (!data || data.length === 0) {
        return { data: undefined };
      }

      const tokenData = data[0];
      return {
        data: {
          tokenId: tokenData.token_id,
          token: tokenData.token,
          expiresAt: tokenData.expires_at,
          usedAt: tokenData.used_at,
          createdAt: tokenData.created_at,
          isExpired: tokenData.is_expired,
          isUsed: tokenData.is_used
        }
      };
    } catch (error) {
      console.error('Exception getting token info via database:', error);
      return {
        error: {
          code: 'DB_GET_TOKEN_INFO_EXCEPTION',
          message: 'Exception occurred during database token info retrieval',
          details: error
        }
      };
    }
  }

  /**
   * Get all active invitation tokens using database function
   * Requirements: 4.1, 4.2
   */
  async getActiveTokensViaDatabase(): Promise<{
    data?: Array<{
      tokenId: string;
      invitationRequestId: string;
      token: string;
      expiresAt: string;
      createdAt: string;
      parentName: string;
      parentEmail: string;
      childName: string;
      invitationStatus: string;
    }>;
    error?: InvitationError;
  }> {
    try {
      const { data, error } = await supabase.rpc('get_active_invitation_tokens');

      if (error) {
        console.error('Error getting active tokens via database:', error);
        return {
          error: {
            code: 'DB_GET_ACTIVE_TOKENS_FAILED',
            message: 'Failed to get active tokens via database function',
            details: error
          }
        };
      }

      const tokens = (data || []).map((token: any) => ({
        tokenId: token.token_id,
        invitationRequestId: token.invitation_request_id,
        token: token.token,
        expiresAt: token.expires_at,
        createdAt: token.created_at,
        parentName: token.parent_name,
        parentEmail: token.parent_email,
        childName: token.child_name,
        invitationStatus: token.invitation_status
      }));

      return { data: tokens };
    } catch (error) {
      console.error('Exception getting active tokens via database:', error);
      return {
        error: {
          code: 'DB_GET_ACTIVE_TOKENS_EXCEPTION',
          message: 'Exception occurred during database active tokens retrieval',
          details: error
        }
      };
    }
  }

  /**
   * Get tokens expiring soon using database function
   * Requirements: 5.1, 5.2
   */
  async getExpiringTokensViaDatabase(daysAhead: number = 7): Promise<{
    data?: Array<{
      tokenId: string;
      invitationRequestId: string;
      token: string;
      expiresAt: string;
      parentName: string;
      parentEmail: string;
      childName: string;
      daysUntilExpiry: number;
    }>;
    error?: InvitationError;
  }> {
    try {
      const { data, error } = await supabase.rpc('get_expiring_invitation_tokens', {
        days_ahead: daysAhead
      });

      if (error) {
        console.error('Error getting expiring tokens via database:', error);
        return {
          error: {
            code: 'DB_GET_EXPIRING_TOKENS_FAILED',
            message: 'Failed to get expiring tokens via database function',
            details: error
          }
        };
      }

      const tokens = (data || []).map((token: any) => ({
        tokenId: token.token_id,
        invitationRequestId: token.invitation_request_id,
        token: token.token,
        expiresAt: token.expires_at,
        parentName: token.parent_name,
        parentEmail: token.parent_email,
        childName: token.child_name,
        daysUntilExpiry: token.days_until_expiry
      }));

      return { data: tokens };
    } catch (error) {
      console.error('Exception getting expiring tokens via database:', error);
      return {
        error: {
          code: 'DB_GET_EXPIRING_TOKENS_EXCEPTION',
          message: 'Exception occurred during database expiring tokens retrieval',
          details: error
        }
      };
    }
  }

  /**
   * Get comprehensive token statistics using database function
   * Requirements: 4.1, 7.5
   */
  async getTokenStatsViaDatabase(): Promise<{
    data?: {
      totalTokens: number;
      activeTokens: number;
      expiredTokens: number;
      usedTokens: number;
      expiringSoon: number;
    };
    error?: InvitationError;
  }> {
    try {
      const { data, error } = await supabase.rpc('get_invitation_token_stats');

      if (error) {
        console.error('Error getting token stats via database:', error);
        return {
          error: {
            code: 'DB_GET_TOKEN_STATS_FAILED',
            message: 'Failed to get token stats via database function',
            details: error
          }
        };
      }

      if (!data || data.length === 0) {
        return {
          data: {
            totalTokens: 0,
            activeTokens: 0,
            expiredTokens: 0,
            usedTokens: 0,
            expiringSoon: 0
          }
        };
      }

      const stats = data[0];
      return {
        data: {
          totalTokens: stats.total_tokens,
          activeTokens: stats.active_tokens,
          expiredTokens: stats.expired_tokens,
          usedTokens: stats.used_tokens,
          expiringSoon: stats.expiring_soon
        }
      };
    } catch (error) {
      console.error('Exception getting token stats via database:', error);
      return {
        error: {
          code: 'DB_GET_TOKEN_STATS_EXCEPTION',
          message: 'Exception occurred during database token stats retrieval',
          details: error
        }
      };
    }
  }

  /**
   * Extend token expiration using database function
   * Requirements: 2.5, 6.2
   */
  async extendTokenExpiryViaDatabase(token: string, additionalDays: number = 30): Promise<{
    success: boolean;
    error?: InvitationError;
  }> {
    try {
      const { data, error } = await supabase.rpc('extend_invitation_token_expiry', {
        token_input: token,
        additional_days: additionalDays
      });

      if (error) {
        console.error('Error extending token expiry via database:', error);
        return {
          success: false,
          error: {
            code: 'DB_EXTEND_TOKEN_EXPIRY_FAILED',
            message: 'Failed to extend token expiry via database function',
            details: error
          }
        };
      }

      return { success: data === true };
    } catch (error) {
      console.error('Exception extending token expiry via database:', error);
      return {
        success: false,
        error: {
          code: 'DB_EXTEND_TOKEN_EXPIRY_EXCEPTION',
          message: 'Exception occurred during database token expiry extension',
          details: error
        }
      };
    }
  }

  /**
   * Get token history for an invitation using database function
   * Requirements: 4.2, 4.4
   */
  async getTokenHistoryViaDatabase(invitationId: string): Promise<{
    data?: Array<{
      tokenId: string;
      token: string;
      createdAt: string;
      expiresAt: string;
      usedAt: string | null;
      status: string;
    }>;
    error?: InvitationError;
  }> {
    try {
      const { data, error } = await supabase.rpc('get_invitation_token_history', {
        invitation_id_input: invitationId
      });

      if (error) {
        console.error('Error getting token history via database:', error);
        return {
          error: {
            code: 'DB_GET_TOKEN_HISTORY_FAILED',
            message: 'Failed to get token history via database function',
            details: error
          }
        };
      }

      const history = (data || []).map((token: any) => ({
        tokenId: token.token_id,
        token: token.token,
        createdAt: token.created_at,
        expiresAt: token.expires_at,
        usedAt: token.used_at,
        status: token.status
      }));

      return { data: history };
    } catch (error) {
      console.error('Exception getting token history via database:', error);
      return {
        error: {
          code: 'DB_GET_TOKEN_HISTORY_EXCEPTION',
          message: 'Exception occurred during database token history retrieval',
          details: error
        }
      };
    }
  }

  /**
   * Clean up expired tokens with detailed reporting using database function
   * Requirements: 7.4
   */
  async cleanupExpiredTokensViaDatabase(): Promise<{
    data?: {
      deletedCount: number;
      cleanupTimestamp: string;
      oldestDeletedToken: string | null;
      newestDeletedToken: string | null;
    };
    error?: InvitationError;
  }> {
    try {
      const { data, error } = await supabase.rpc('cleanup_expired_tokens_detailed');

      if (error) {
        console.error('Error cleaning up expired tokens via database:', error);
        return {
          error: {
            code: 'DB_CLEANUP_TOKENS_FAILED',
            message: 'Failed to clean up expired tokens via database function',
            details: error
          }
        };
      }

      if (!data || data.length === 0) {
        return {
          data: {
            deletedCount: 0,
            cleanupTimestamp: new Date().toISOString(),
            oldestDeletedToken: null,
            newestDeletedToken: null
          }
        };
      }

      const result = data[0];
      return {
        data: {
          deletedCount: result.deleted_count,
          cleanupTimestamp: result.cleanup_timestamp,
          oldestDeletedToken: result.oldest_deleted_token,
          newestDeletedToken: result.newest_deleted_token
        }
      };
    } catch (error) {
      console.error('Exception cleaning up expired tokens via database:', error);
      return {
        error: {
          code: 'DB_CLEANUP_TOKENS_EXCEPTION',
          message: 'Exception occurred during database token cleanup',
          details: error
        }
      };
    }
  }

  /**
   * Validate token with comprehensive information using database function
   * Requirements: 2.3, 6.2
   */
  async validateTokenViaDatabase(token: string): Promise<{
    data?: {
      isValid: boolean;
      validationStatus: string;
      invitationId: string | null;
      parentEmail: string | null;
      childName: string | null;
      childAge: number | null;
      expiresAt: string | null;
      usedAt: string | null;
      invitationStatus: string | null;
      daysUntilExpiry: number | null;
    };
    error?: InvitationError;
  }> {
    try {
      const { data, error } = await supabase.rpc('validate_invitation_token_detailed', {
        token_input: token
      });

      if (error) {
        console.error('Error validating token via database:', error);
        return {
          error: {
            code: 'DB_VALIDATE_TOKEN_FAILED',
            message: 'Failed to validate token via database function',
            details: error
          }
        };
      }

      if (!data || data.length === 0) {
        return {
          data: {
            isValid: false,
            validationStatus: 'token_not_found',
            invitationId: null,
            parentEmail: null,
            childName: null,
            childAge: null,
            expiresAt: null,
            usedAt: null,
            invitationStatus: null,
            daysUntilExpiry: null
          }
        };
      }

      const result = data[0];
      return {
        data: {
          isValid: result.is_valid,
          validationStatus: result.validation_status,
          invitationId: result.invitation_id,
          parentEmail: result.parent_email,
          childName: result.child_name,
          childAge: result.child_age,
          expiresAt: result.expires_at,
          usedAt: result.used_at,
          invitationStatus: result.invitation_status,
          daysUntilExpiry: result.days_until_expiry
        }
      };
    } catch (error) {
      console.error('Exception validating token via database:', error);
      return {
        error: {
          code: 'DB_VALIDATE_TOKEN_EXCEPTION',
          message: 'Exception occurred during database token validation',
          details: error
        }
      };
    }
  }

  /**
   * Use invitation token (mark as used) using database function
   * Requirements: 2.4, 2.5
   */
  async useTokenViaDatabase(token: string, userId: string): Promise<{
    success: boolean;
    error?: InvitationError;
  }> {
    try {
      const { data, error } = await supabase.rpc('use_invitation_token', {
        token_input: token,
        user_id_input: userId
      });

      if (error) {
        console.error('Error using token via database:', error);
        return {
          success: false,
          error: {
            code: 'DB_USE_TOKEN_FAILED',
            message: 'Failed to use token via database function',
            details: error
          }
        };
      }

      return { success: data === true };
    } catch (error) {
      console.error('Exception using token via database:', error);
      return {
        success: false,
        error: {
          code: 'DB_USE_TOKEN_EXCEPTION',
          message: 'Exception occurred during database token usage',
          details: error
        }
      };
    }
  }
}

// Export a singleton instance
export const invitationTokenDatabaseService = new InvitationTokenDatabaseService();