// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sutvexycbiiarpkugzpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1dHZleHljYmlpYXJwa3VnenB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDU4MjAsImV4cCI6MjA3MTI4MTgyMH0.4elojlOCOE_lk2JRZRkQX7feJMbuMTvYKSez5o5d_HA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);